# DIA 1 EJECICIOS DEL NIVEL 3

# EJEMPLOS: NUMBER / NUMEROS 
int_num = 50                                  # numeros enteros 
float_num = 3.14                              # numero con decimales
complex_num = 4 + 5j                          # numeros irreales o complejos
# EJEMPLOS: STRING / CADENAS 
name = "Guayaber"
# EJEMPLOS: BOOLEAN / VRD O FALSO
is_happy = True                               # los booleanos definen si es es verdad algo un ejemplo simple es 3 es igual a 3 ? si
# EJMPLOS: LIST / LISTAS 
languages = ["Python", "JavaScript", "C++"]
# EJEMPLOS: TUPLE / TUPLA 
coordinates = (10.5, 20.8)                    
# EJEMPLOS: SET / SET?
unique_numbers = {1, 2, 3}                    # algo unico no tangible que se puede especificar y no se puede repitir 
#EJEMPLOS:  DICTIONARY / DICCIONARIO
person = {                                    # es como una base de datos 
    "name": "Principe guayaber",
    "country": "Mexico",
    "age": 18
}